OOP school library: add basic UI
bobb-Rob/school-library pull request #4
Opened 2022-08-26 16:33 UTC by bobb-Rob

### I Implemented the following: 

- Create a app.rb file that will serve as your console app entry-point. It should have methods that do the following:

     - List all books.
     - List all people.
     - Create a person (teacher or student, not a plain Person).
     - Create a book.
     - Create a rental.
     - List all rentals for a given person id.

- In your main.rb define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:

    - Present the user with a list of options to perform.
    - Lets users choose an option.
    - If needed, ask for parameters for the option.
    - Have a way to quit the app.

2022-08-26 16:47 UTC, Rustamxon7 requested changes
Hi @bobb-Rob, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
_Your project is almost complete!_
_No Linters errors_


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/app.rb
> +class App
You made a great effort to make this project! However, some errors need to be filled in!

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/app.rb
> +    age = gets.chomp
If I give to student's age a wrong argument, it is not rising an error. 
You can see the image here:

<img width="529" alt="Screen Shot 2022-08-26 at 21 39 06" src="https://user-images.githubusercontent.com/69011963/186952727-0eff0bf5-eebd-440a-bf25-68dacdc9d557.png">

- [ ] Kindly fix this issue. When you give a wrong argument, make sure it shows an error!

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/app.rb
> +    age = gets.chomp
- [ ] The same error as I mentioned above!

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/app.rb
> +    print 'Date (YYYY/MM/DD) : '
- [ ] The same error is present here:


<img width="375" alt="Screen Shot 2022-08-26 at 21 38 55" src="https://user-images.githubusercontent.com/69011963/186952980-a85efda6-2871-42b2-8862-eff3eabc9a7b.png">

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/main.rb
> +    5 - Create a rental.
When I tried to create a rental, it broke the app:

<img width="707" alt="Screen Shot 2022-08-26 at 21 37 17" src="https://user-images.githubusercontent.com/69011963/186953204-9143268c-1054-4153-85ed-8accd8ea5de2.png">

- [ ] Make sure all errors are handled!

2022-08-26 16:47 UTC, Rustamxon7 commented on classes/main.rb
> +main
[OPTIONAL] Kindly make sure you added MIT license to your project.

2022-08-27 08:49 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @bobb-Rob , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well implemented suggested changes.

### Optional suggestions :arrow_down_small: 

- [ ] The commit message should be written in the imperative tense. `Ex: "Fix bug" instead of "Fixed bug".` [For more details.](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-27 10:55 UTC, merged